web: gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app --bind 0.0.0.0:$PORT
worker: celery -A backend.worker.tasks worker --loglevel=info
beat: celery -A backend.worker.tasks beat --loglevel=info
