web: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:$PORT
worker: celery -A worker.tasks worker --loglevel=info --concurrency=1 & celery -A worker.tasks beat --loglevel=info & wait -n
