"""Documented Market Tools leagues for the Odds API snapshot. No provider HTTP."""

from __future__ import annotations

# sport_group drives the customer sport selector. Soccer uses a second league selector.
LEAGUES = (
    {
        "key": "americanfootball_nfl",
        "title": "NFL",
        "sport_group": "NFL",
        "selector": "nfl",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Moneyline", "spreads": "Spread", "totals": "Over/Under"},
        "reuse_saved": True,
    },
    {
        "key": "americanfootball_ncaaf",
        "title": "NCAAF",
        "sport_group": "NCAAF",
        "selector": "ncaaf",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Moneyline", "spreads": "Spread", "totals": "Over/Under"},
        "reuse_saved": True,
    },
    {
        "key": "baseball_mlb",
        "title": "MLB",
        "sport_group": "MLB",
        "selector": "mlb",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Moneyline", "spreads": "Run Line", "totals": "Total Runs"},
        "reuse_saved": True,
    },
    {
        "key": "icehockey_nhl",
        "title": "NHL",
        "sport_group": "NHL",
        "selector": "nhl",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Moneyline", "spreads": "Puck Line", "totals": "Total Goals"},
        "reuse_saved": False,
    },
    {
        "key": "basketball_nba",
        "title": "NBA",
        "sport_group": "NBA",
        "selector": "nba",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Moneyline", "spreads": "Spread", "totals": "Over/Under"},
        "reuse_saved": False,
    },
    {
        "key": "basketball_ncaab",
        "title": "NCAAB",
        "sport_group": "NCAAB",
        "selector": "ncaab",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Moneyline", "spreads": "Spread", "totals": "Over/Under"},
        "reuse_saved": False,
        "sample_if_missing_from_catalog": False,
        "docs_note": "Documented key basketball_ncaab. Not present in this in-season catalog snapshot.",
    },
    {
        "key": "basketball_wnba",
        "title": "WNBA",
        "sport_group": "WNBA",
        "selector": "wnba",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Moneyline", "spreads": "Spread", "totals": "Over/Under"},
        "reuse_saved": False,
    },
    {
        "key": "soccer_usa_mls",
        "title": "MLS",
        "sport_group": "Soccer",
        "selector": "soccer",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Home / Draw / Away", "spreads": "Handicap", "totals": "Total Goals"},
        "reuse_saved": False,
    },
    {
        "key": "soccer_epl",
        "title": "England Premier League",
        "sport_group": "Soccer",
        "selector": "soccer",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Home / Draw / Away", "spreads": "Handicap", "totals": "Total Goals"},
        "reuse_saved": False,
    },
    {
        "key": "soccer_spain_la_liga",
        "title": "Spain La Liga",
        "sport_group": "Soccer",
        "selector": "soccer",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Home / Draw / Away", "spreads": "Handicap", "totals": "Total Goals"},
        "reuse_saved": False,
    },
    {
        "key": "soccer_italy_serie_a",
        "title": "Italy Serie A",
        "sport_group": "Soccer",
        "selector": "soccer",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Home / Draw / Away", "spreads": "Handicap", "totals": "Total Goals"},
        "reuse_saved": False,
    },
    {
        "key": "soccer_germany_bundesliga",
        "title": "Germany Bundesliga",
        "sport_group": "Soccer",
        "selector": "soccer",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Home / Draw / Away", "spreads": "Handicap", "totals": "Total Goals"},
        "reuse_saved": False,
    },
    {
        "key": "soccer_france_ligue_one",
        "title": "France Ligue 1",
        "sport_group": "Soccer",
        "selector": "soccer",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Home / Draw / Away", "spreads": "Handicap", "totals": "Total Goals"},
        "reuse_saved": False,
    },
    {
        "key": "soccer_uefa_champs_league",
        "title": "UEFA Champions League",
        "sport_group": "Soccer",
        "selector": "soccer",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Home / Draw / Away", "spreads": "Handicap", "totals": "Total Goals"},
        "reuse_saved": False,
    },
    {
        "key": "soccer_uefa_europa_league",
        "title": "UEFA Europa League",
        "sport_group": "Soccer",
        "selector": "soccer",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Home / Draw / Away", "spreads": "Handicap", "totals": "Total Goals"},
        "reuse_saved": False,
    },
    {
        "key": "soccer_uefa_europa_conference_league",
        "title": "UEFA Europa Conference League",
        "sport_group": "Soccer",
        "selector": "soccer",
        "kind": "match",
        "markets": ("h2h", "spreads", "totals"),
        "labels": {"h2h": "Home / Draw / Away", "spreads": "Handicap", "totals": "Total Goals"},
        "reuse_saved": False,
    },
    {
        "key": "golf_masters_tournament_winner",
        "title": "Masters Tournament Winner",
        "sport_group": "Golf",
        "selector": "golf",
        "kind": "outright",
        "markets": ("outrights",),
        "labels": {"outrights": "Tournament Winner"},
        "reuse_saved": False,
        "golf_coverage": "Documented major tournament-winner market only. Not weekly PGA Tour coverage.",
    },
    {
        "key": "golf_pga_championship_winner",
        "title": "PGA Championship Winner",
        "sport_group": "Golf",
        "selector": "golf",
        "kind": "outright",
        "markets": ("outrights",),
        "labels": {"outrights": "Tournament Winner"},
        "reuse_saved": False,
        "golf_coverage": "Documented major tournament-winner market only. Not weekly PGA Tour coverage.",
    },
    {
        "key": "golf_the_open_championship_winner",
        "title": "The Open Winner",
        "sport_group": "Golf",
        "selector": "golf",
        "kind": "outright",
        "markets": ("outrights",),
        "labels": {"outrights": "Tournament Winner"},
        "reuse_saved": False,
        "golf_coverage": "Documented major tournament-winner market only. Not weekly PGA Tour coverage.",
    },
    {
        "key": "golf_us_open_winner",
        "title": "US Open Winner",
        "sport_group": "Golf",
        "selector": "golf",
        "kind": "outright",
        "markets": ("outrights",),
        "labels": {"outrights": "Tournament Winner"},
        "reuse_saved": False,
        "golf_coverage": "Documented major tournament-winner market only. Not weekly PGA Tour coverage.",
    },
)

SPORT_SELECTOR = (
    {"id": "nfl", "label": "NFL"},
    {"id": "ncaaf", "label": "NCAAF"},
    {"id": "mlb", "label": "MLB"},
    {"id": "nhl", "label": "NHL"},
    {"id": "nba", "label": "NBA"},
    {"id": "ncaab", "label": "NCAAB"},
    {"id": "wnba", "label": "WNBA"},
    {"id": "soccer", "label": "Soccer"},
    {"id": "golf", "label": "Golf"},
)

PROP_MARKET_NAMES = {
    "player_pass_tds": "Pass Touchdowns",
    "batter_hits": "Batter Hits",
}

MARKET_PERIOD = "game"


def league_by_key(key: str) -> dict | None:
    for row in LEAGUES:
        if row["key"] == key:
            return row
    return None
