"""Official The Odds API source record. No secrets. Isolated development only."""

SOURCE = {
    "provider": "The Odds API",
    "docs": "https://the-odds-api.com/liveapi/guides/v4/",
    "terms": "https://the-odds-api.com/terms-and-conditions.html",
    "markets_list": "https://the-odds-api.com/sports-odds-data/betting-markets.html",
    "host": "https://api.the-odds-api.com",
    "sports_sampled": {
        "americanfootball_nfl": "NFL",
        "americanfootball_ncaaf": "NCAAF",
        "baseball_mlb": "MLB",
        "icehockey_nhl": "NHL",
        "basketball_nba": "NBA",
        "basketball_ncaab": "NCAAB (documented; not in this in-season catalog)",
        "basketball_wnba": "WNBA",
        "soccer_usa_mls": "MLS",
        "soccer_epl": "EPL",
        "soccer_spain_la_liga": "La Liga",
        "soccer_italy_serie_a": "Serie A",
        "soccer_germany_bundesliga": "Bundesliga",
        "soccer_france_ligue_one": "Ligue 1",
        "soccer_uefa_champs_league": "UEFA Champions League",
        "soccer_uefa_europa_league": "UEFA Europa League",
        "soccer_uefa_europa_conference_league": "UEFA Europa Conference League",
        "golf_masters_tournament_winner": "Masters Winner",
        "golf_pga_championship_winner": "PGA Championship Winner",
        "golf_the_open_championship_winner": "The Open Winner",
        "golf_us_open_winner": "US Open Winner",
    },
    "featured_markets": ["h2h", "spreads", "totals"],
    "region_this_test": "us",
    "credit_formula_featured": "markets_specified × regions (empty body costs 0)",
    "credit_formula_event_odds": "unique_markets_returned × regions (empty body costs 0)",
    "sports_endpoint_cost": 0,
    "events_endpoint_cost": 0,
    "event_markets_endpoint_cost": 1,
    "scores_endpoint_cost_without_days_from": 1,
    "scores_endpoint_cost_with_days_from": 2,
    "scores_schema_has_period_clock": False,
    "historical_endpoints": "paid plans only — not called",
    "empty_featured_odds_cost": 0,
    "empty_event_odds_cost": 0,
    "us_region_bookmakers_documented": [
        "betonlineag", "betmgm", "betrivers", "betus", "bovada",
        "williamhill_us", "draftkings", "fanatics", "fanduel", "lowvig", "mybookieag",
    ],
    "us_paid_subscription_only_books": ["williamhill_us (Caesars)", "fanatics"],
    "us2_region": "documented, not sampled this test",
    "customer_facing_use": (
        "Terms (updated 31 August 2026) permit storing data indefinitely and displaying it in a UI, "
        "including commercial use, provided the data is not resold as a standalone data feed/API."
    ),
    "storage": "Storing and retaining data indefinitely is permitted.",
    "key_handling": "Keep API key private; quota depletes if leaked. Never put the key in browser code.",
    "homepage_plans_usd": {
        "source": "https://the-odds-api.com/ (direct homepage fetch 403 this session; prices from official homepage search snippets dated 2026-09-30)",
        "free": {"price_usd": 0, "credits_per_month": 500},
        "20k": {"price_usd": 30, "credits_per_month": 20000},
        "100k": {"price_usd": 59, "credits_per_month": 100000},
        "5m": {"price_usd": 119, "credits_per_month": 5000000},
        "15m": {"price_usd": 249, "credits_per_month": 15000000},
    },
    "compatibility_gaps": [
        "Odds API source IDs are namespaced as oddsapi:{sport_key}:{id} and are never returned as SGO event IDs.",
        "No SGO event ids, Fair Odds from SGO, or nested /v2/events cache in this adapter.",
        "Period, alternate, and unsampled player-prop markets remain unavailable.",
        "Caesars and Fanatics are documented as paid-subscription-only on region us.",
        "Parlay math is an SB ME product of decimals, not a bookmaker SGP quote.",
    ],
    "untested_coverage": [
        "uk/eu/au/ca/fr/se/fi regions",
        "us2, us_dfs, us_ex bookmakers",
        "period markets (quarters, halves, innings)",
        "alternate lines",
        "player props beyond sampled events",
        "NCAAB player props (no saved events)",
        "soccer props outside EPL/MLS sample and undocumented leagues",
        "weekly PGA Tour stroke-play markets",
        "NCAAB regular-season games (key documented, not in this catalog snapshot)",
    ],
}
